### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by NeilsUltimateLab** [hebertialmeida/MarkdownSyntax#2]
When adding this dependency via Xcode below error is displayed in package resolution.

![Screenshot 2020-07-11 at 4 15 17 PM](https://user-images.githubusercontent.com/23612211/87222516-bbffd000-c391-11ea-954f-4c98482986bc.png)

`because no versions of MarkdownSyntax match the requirement 1.0.1..<2.0.0 and package markdownsyntax is required using a version-based requirement and it depends on unversion package swift-cmark-gfm, MarkdownSyntax >=1.0.0 is forbidden.
And because root depends on MarkdownSyntax 1.0.0..<2.0.0, version solving failed.`

![Screenshot 2020-07-11 at 4 12 43 PM](https://user-images.githubusercontent.com/23612211/87222451-5c092980-c391-11ea-8c89-2b31222881af.png)

Any work-around resolving this?
Thanks.

**Comment by hebertialmeida** [comment]
You can try to use `exact` instead of `up to next version` or you can try to point to master branch and see if it works. I did a fair amount of change after 1.0.0 I believe and didn't tag yet.

Let me know if that works for you.

**Comment by NeilsUltimateLab** [comment]
Thanks for the reply @hebertialmeida.
Yes if I select Branch: master option then it also works 🎉.
But at the compile time it asks for the iOS 9 minimum deployment target.

**Comment by hebertialmeida** [comment]
I believe Swift Packages are iOS 9+

**Comment by NeilsUltimateLab** [comment]
Yes, since Package.swift file having platform declaration to `.iOS(.v8)` was causing the error.
![Screenshot 2020-07-17 at 11 38 51 PM](https://user-images.githubusercontent.com/23612211/87817560-cdac1080-c886-11ea-8c1a-d37c02ff374b.png)

So I forked your repo and updated to `.iOS(.v9)`, then it worked. 🎉. 

I also tried to add tags to forked repo but found that if any of the dependency is having 0.xx.x tag (in our case `cmark_gfm ` having 0.29.0 tag) then its failing for the `upToNextMajor` option (may be Xcode/SwiftPM bug but not sure.).

So I also forked that and added tag with 1.0.0 then it worked for `upToNextMajor` option too. 😊😇
Thanks.

**Comment by hebertialmeida** [comment]
Oh, nice! can you open a PR so I can update it?

**Comment by NeilsUltimateLab** [comment]
@hebertialmeida I opened pull requests.
Thanks.

**Comment by hebertialmeida** [comment]
Nice, I have merged.
