### ISSUE TITLE
No explicit grant of open source license

### ISSUE THREAD

**Issue by mklca** [hebertialmeida/MarkdownSyntax#5]
The source code does not appear to have any licensing statement except for the copyright statements in the source code files themselves, e.g., [this one](https://github.com/hebertialmeida/MarkdownSyntax/blob/a8731ec2e5f532f90c650770f9d54d79feaced80/Sources/MarkdownSyntax/Markdown.swift#L6):

    //  Copyright © 2019 Heberti Almeida. All rights reserved.

It would be helpful if the author clarified the licensing for this repository by adding a LICENSE or COPYING file and amending their copyright statements.

**Comment by hebertialmeida** [comment]
Hey @mklca! Totally forgot about that, the licence should be MIT. I've just added that to the repo https://github.com/hebertialmeida/MarkdownSyntax/blob/master/LICENSE
